# -*- coding: utf-8 -*-
"""exerciciospython01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JL5Yx4h2L3ItDKkZ3TXRMi1oMuYIDItd
"""

n1 = int(input('Digite um número: '))
for a in range(1, 11):
  print(f"{n1} x {a} = {n1*a}")

# Crie um programa que leia quanto dinheiro uma pessoa tem na carteira e mostre quantos dólares ela pode comprar
# Considere US$1,00 = R$3,27
n1 = float(input('Digite a quantia em reais: R$'))
dolar = n1/3.27
print(f'A quantia de {n1:.2f} reais é de {dolar:.2f} dolares')

# Faça um programa que leia a largura e a altura de uma parede em metros, calcule a sua área e a quantidade de tinta necessária para pintá-la, sabendo que cada litro de tinta pinta uma área de 2 metros quadrados.
larg = float(input('Digite a largura em metros: '))
alt = float(input('Digite a altura em metros: '))
area = larg*alt
tinta = area/2
print(f'{area:.2f}m² necessitam de {tinta:.1f} litros de tinta')

# Faça um algoritmo que leia o preço de um produto e mostre seu novo preço com 5% de desconto.
preco = float(input('Digite o valor do produto: '))
desconto = preco*0.05
valor_novo = preco - desconto
print(f'O valor incial do produto é R${preco:.2f} e com o desconto de R${desconto:.2f} o produto passou a custar R${valor_novo:.2f}')

# Faça um algoritmo que leia o salário de um funcionário e mostre seu novo salário com 15% de aumento
salario = float(input('Digite o valor do salário: '))
aumento = salario*0.15
novo_sal = salario+aumento
print(f'O salário de R${salario:.2f} ganhou um aumento de R${aumento:.2f}.\nO salário agora é de R${novo_sal:.2f}')

# Escreva um programa que converta uma temperatura digitando em graus Celsius e converta para graus Fahrenheit
celcius = float(input('Digite a temperatura em graus Celcius: '))
fahrenheit = celcius*1.8+32
print(f'A conversão de {celcius:.1f}ºC são {fahrenheit:.1f}ºF')

# Escreva um programa que pergunte a quantidade de Km percorridos por um carro alugado e a quantidade de dias pelos
# quais ele foi alugado. Calcule o preço a pagar, sabendo que o carro custa R$60 por dia e R$0,15 por Km rodado.
km_rodado = float(input('Digite a quantidade de Km rodados: '))
dias = int(input('Digite a quantidade de dias que o carro foi alugado: '))
preco = 60 * dias + km_rodado * 0.15
print(f'O custo do alugel de {dias} dias e {km_rodado}km rodados foi de R${preco}')

# Crie um programa que leia um número Real qualquer pelo teclado e mostre na tela a sua porção Inteira
nro = float(input('Digite um número real: '))
print(f'O valor digitado é:{nro} e a sua parte inteira é {int(nro)}')