# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12fowY7wBLU1QXd60Us_9ulZdDcISSUXz
"""

# Exercício 006 - Dobro, Triplo, Raiz Quadrada
# Crie um algoritmo que leia um número e mostre o seu dobro, triplo e raiz quadrada.
n1 = int(input('Digite o primeiro número:'))
dobro = n1 * 2
triplo = n1 * 3
raiz = n1 ** (1/2)

print(dobro)
print(triplo)
print(raiz)

# Exercício 007 - Média Aritmética
# Desenvolva um programa que leia as duas notas de um aluno.

n1 = int(input('Digite a primeira nota: '))
n2 = int(input('Digite a segunda nota: '))
media = (n1+n2)/2

print(media)

# Exercício 008 - Conversor de Medidas
# Escreva um programa que leia um valor em metros e o exiba convertido em centímetros e milímetros.

n1 = int(input('Digite o valor em metros: '))
centimetros = n1*100
milimetros = n1*1000

print(n1)
print(centimetros)
print(milimetros)

# Exercício 9 - Tabuada
# Faça um programa que leia um número Inteiro qualquer e mostre na tela a sua tabuada

def tab(n1, b):
  mult = n1*b
  print(f"{n1} * {b} = {mult}")

n1 =